SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (
        SELECT MAX(I.SIZE_OF_COLONY)
        FROM ECOLI_DATA I
        WHERE YEAR(I.DIFFERENTIATION_DATE) = YEAR(E.DIFFERENTIATION_DATE)
    ) - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
ORDER BY YEAR ASC, YEAR_DEV ASC;