SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I, FISH_NAME_INFO N
WHERE I.FISH_TYPE = N.FISH_TYPE AND I.LENGTH = (
      SELECT MAX(F.LENGTH)
      FROM FISH_INFO F
      WHERE F.FISH_TYPE = I.FISH_TYPE
  )
ORDER BY I.ID;
