SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT F
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
  AND PRICE = (
      SELECT MAX(P.PRICE)
      FROM FOOD_PRODUCT P
      WHERE P.CATEGORY = F.CATEGORY
  )
ORDER BY PRICE DESC;